name: DevOps Course Rules Enforcement
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout latest version of repo
      - uses: actions/checkout@v2
        name: "Checkout"
      - run:
          pip install PyGithub
      - run:
          python check_rules.py ${{ secrets.GITHUB_TOKEN }} ${{toJson(github.event)}}
