name: DevOps Course Rules Enforcement
on:
  pull_request:
    branches:
      - main
    paths:
      - contributions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout latest version of repo
      - uses: actions/checkout@v2
        name: "Checkout"
      - run:
          pip install PyGithub
      - run:
          echo ${{github.repository}}
          echo ${{ github.repo.name }}
          echo "$GITHUB_REPOSITORY"
          echo "$REPOSITORY_NAME"          
          python check_rules.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} ${{ github.repo.name }}
